name: juno
services:
  postgresql:
    container_name: juno-postgresql
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped
  keycloak:
    container_name: juno-keycloak
    image: quay.io/keycloak/keycloak:26.3.4
    ports:
      - 8080:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
    command: ["start-dev"]
    restart: unless-stopped
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  postgresql_data:
  keycloak_data: